// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicCell: typeof import('./src/components/BasicCell.vue')['default']
    'Carbon:notificationFilled': typeof import('virtual:vite-icons/carbon/notification-filled')['default']
    'Carbon:notificationOffFilled': typeof import('virtual:vite-icons/carbon/notification-off-filled')['default']
    CarbonAiStatusInProgress: typeof import('virtual:vite-icons/carbon/ai-status-in-progress')['default']
    CarbonDeployRules: typeof import('virtual:vite-icons/carbon/deploy-rules')['default']
    CarbonEmail: typeof import('virtual:vite-icons/carbon/email')['default']
    CarbonFaceCool: typeof import('virtual:vite-icons/carbon/face-cool')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonVirtualPrivateCloud: typeof import('virtual:vite-icons/carbon/virtual-private-cloud')['default']
    Cell: typeof import('./src/components/Cell.vue')['default']
    CryptoNavBar: typeof import('./src/components/CryptoNavBar.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GetDifficulty: typeof import('./src/components/GetDifficulty.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InternalLink: typeof import('./src/components/InternalLink.vue')['default']
    Links1: typeof import('./src/components/Links1.md')['default']
    Links2: typeof import('./src/components/Links2.md')['default']
    Links3: typeof import('./src/components/Links3.md')['default']
    LinkTemplate: typeof import('./src/components/LinkTemplate.vue')['default']
    Loader: typeof import('./src/components/Loader.md')['default']
    NavBarItem: typeof import('./src/components/NavBarItem.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    Subscriptions: typeof import('./src/components/Subscriptions.vue')['default']
    SudokuGame: typeof import('./src/components/SudokuGame.vue')['default']
    TimeAgo: typeof import('./src/components/TimeAgo.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
    Transactions: typeof import('./src/components/Transactions.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}

export { }
