// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicCell: typeof import('./components/BasicCell.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    CryptoNavBar: typeof import('./components/CryptoNavBar.vue')['default']
    CryptoServices: typeof import('./components/CryptoServices.vue')['default']
    CryptoTransactions: typeof import('./components/CryptoTransactions.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GetDifficulty: typeof import('./components/GetDifficulty.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    InternalLink: typeof import('./components/InternalLink.vue')['default']
    Links1: typeof import('./components/Links1.md')['default']
    Links2: typeof import('./components/Links2.md')['default']
    Links3: typeof import('./components/Links3.md')['default']
    LinkTemplate: typeof import('./components/LinkTemplate.vue')['default']
    Loader: typeof import('./components/Loader.md')['default']
    NavBarItem: typeof import('./components/NavBarItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    ServiceCard: typeof import('./components/ServiceCard.vue')['default']
    Subscriptions: typeof import('./components/Subscriptions.vue')['default']
    SudokuGame: typeof import('./components/SudokuGame.vue')['default']
    TimeAgo: typeof import('./components/TimeAgo.vue')['default']
    TimeLine: typeof import('./components/TimeLine.vue')['default']
    TransactionCard: typeof import('./components/TransactionCard.vue')['default']
    Transactions: typeof import('./components/Transactions.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}

export { }
