// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Links1: typeof import('./src/components/Links1.md')['default']
    Links2: typeof import('./src/components/Links2.md')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
