export const history = [
  {
    key: 1,
    color: 'red',
    name: 'Logo',
    link: 'https://en.wikipedia.org/wiki/Logo_(programming_language)',
    year: '1984',
    text: 'Summer class in Cairo-Egypt',
  },
  {
    key: 2,
    color: 'orange',
    name: 'Basic',
    link: 'https://en.wikipedia.org/wiki/BASIC"',
    year: '1988',
    text: 'Beginner\'s All-purpose Symbolic Instruction Code',
  },
  {
    key: 3,
    color: 'magenta',
    name: 'Visual Basic',
    link: 'https://en.wikipedia.org/wiki/Visual_Basic',
    year: '1998',
    text: 'I aced it with A+ - LCC',
  },
  {
    key: 4,
    color: 'green',
    name: 'Java',
    link: 'https://en.wikipedia.org/wiki/Java_(programming_language)',
    year: '1999',
    text: 'Data Strucure and Algorithms - LCC',
  },
  {
    key: 5,
    color: 'blue',
    name: 'C++',
    link: 'https://en.wikipedia.org/wiki/C%2B%2B',
    year: '2000',
    text: 'Tough cookie, I made it alive -  UofO',
  },
  {
    key: 6,
    color: 'purple',
    name: 'MySQL',
    link: 'https://en.wikipedia.org/wiki/MySQL',
    year: '2000',
    text: 'Tutoring for stdents - LCC',
  },
  {
    key: 7,
    color: 'brown',
    name: 'Microsoft Access',
    link: 'https://en.wikipedia.org/wiki/Microsoft_Access',
    year: '2001',
    text: 'Tutoring for students - UofO',
  },
  {
    key: 8,
    color: 'orange',
    name: 'Visual Basic',
    link: 'https://en.wikipedia.org/wiki/Visual_Basic',
    year: '2003',
    text: 'NBA Project @ ERC',
  },
  {
    key: 9,
    color: 'teal',
    name: 'ASP/VB',
    link: 'https://en.wikipedia.org/wiki/Active_Server_Pages',
    year: '2005-2012',
    text: 'CRM Fullstack @ SS&K',
  },
  {
    key: 10,
    color: 'gray',
    name: 'HTML',
    link: 'https://en.wikipedia.org/wiki/HTML',
    year: '2005-2012',
    text: 'CRM UI @ SS&K',
  },
  {
    key: 11,
    color: 'darkgreen',
    name: 'MsSQL',
    link: 'https://en.wikipedia.org/wiki/Microsoft_SQL_Server',
    year: '2005-2012',
    text: 'CRM Storage @ SS&K',
  },
  {
    key: 12,
    color: 'chocolate',
    name: 'PHP',
    link: 'https://en.wikipedia.org/wiki/PHP"',
    year: '2013',
    text: 'PHP Developer @ Tracy PMI',
  },
  {
    key: 13,
    color: 'orange',
    name: 'HTML5',
    link: 'https://en.wikipedia.org/wiki/HTML5',
    year: '2012',
    text: 'Web developer @ Tracy PMI',
  },
  {
    key: 14,
    color: 'brown',
    name: 'BootStrap 3',
    link: 'https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)',
    year: '2013',
    text: 'Frontend Developer @ Amitnet',
  },
  {
    key: 15,
    color: 'red',
    name: 'jQuery',
    link: 'https://en.wikipedia.org/wiki/JQuery',
    year: '2013',
    text: 'Development @ Tracy PMI, Amitnet Solutions & Finance Magnets',
  },
  {
    key: 16,
    color: 'blueviolet',
    name: 'React',
    link: 'https://en.wikipedia.org/wiki/React_(JavaScript_library)',
    year: '2015',
    text: 'Frontend @ Luneve Solutions',
  },
  {
    key: 17,
    color: 'green',
    name: 'Vue2',
    link: 'https://en.wikipedia.org/wiki/Vue.js',
    year: '2017',
    text: 'Frontend @ Luneve Solutions',
  },
  {
    key: 18,
    color: 'orange',
    name: 'Angular7',
    link:
            'https://en.wikipedia.org/wiki/Angular_(application_platform)#Version_7',
    year: '2018',
    text: 'Frontend @ Luneve Solutions',
  },
  {
    key: 19,
    color: 'purple',
    name: 'Python(Pandas)',
    link: 'https://en.wikipedia.org/wiki/Pandas_(software)',
    year: '2018',
    text:
            'NBA Stats, financial reporting, excel generations. @Luneve Solutions',
  },
  {
    key: 20,
    color: 'teal',
    name: 'Go',
    link: 'https://golang.org/#',
    year: '2018',
    text:
            'Online classes, Udemy Academy, Youtube lessons and home exercises.',
  },
  {
    key: 21,
    color: 'blue',
    name: 'Quasar',
    link: 'https://quasar.dev/',
    year: '2019',
    text:
            'Amaizing Vue Framework, SPA, PWA, SSR, Cordova, Electron, Capacitor and more.',
  },
  {
    key: 22,
    color: 'purple',
    name: 'AWS',
    link: 'https://docs.amplify.aws/lib/q/platform/js',
    year: '2020',
    text: 'Integrating with AWS services using Amplify CLI.',
  },
  {
    key: 23,
    color: 'palevioletred',
    name: 'Self Learning',
    link: 'https://waelio.com',
    year: 'Today...',
    text:
            'Pretty much daily, I perform at least one of following: reading an article, attending an online seminar, watching a YouTube lesson or simply refactoring one of my projects.',
  },
]
