/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6df3673c-2d28-47aa-895a-297c482db6d1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_k1NGnpj3K",
    "aws_user_pools_web_client_id": "42124kba906djo8mnir7gfqoge",
    "oauth": {
        "domain": "portfolio357ad254-357ad254-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://waelio.com/auth/",
        "redirectSignOut": "https://waelio.com/auth/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://vmbn5qt2jbc4bhxh6skuy7sjde.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_user_files_s3_bucket": "portfolio5ab9269805c84546bf01c43db321bf04210752-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
