/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:57769274-d0de-4a62-99d9-3a40cbe0ebbd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BkD2R3bjW",
    "aws_user_pools_web_client_id": "1ad0455rde18h4dorn5q96njvh",
    "oauth": {}
};


export default awsmobile;
